# You can configure zstd-jsonl-filter here
# Check https://github.com/uniQIndividual/zstd-jsonl-filter for the documentation

# Input Parameters
input = "./"

# Output Parameters
output = "./"
suffix = "_filtered"
file_extension = ""
no_write = false

# Output as zstd?
zstd = false
compression_level = 0
window_log_max = 27

# Regex Filter
pattern = "^"

# Performance
threads = 0
buffer = 4096
quiet = false